In [0]:
import pandas as pd
import numpy as np
%matplotlib inline
import seaborn as sns
import matplotlib.pyplot as plt

from google.cloud import bigquery # Library for connecting with the bigquery

from google.oauth2 import service_account

### Accessing the BigQuery Account

In [0]:
credentials = service_account.Credentials.from_service_account_file('/path/to/service-account.json')

project_id = 'your-project-id'

client = bigquery.Client(credentials= credentials,project=project_id)

private_key = '/path/to/service-account.json'

## Getting Start with the Script
1. First create a folder and copy this pyhton file as well as the excel sheet having swoo_id
2. Run the step 2 and give the name of that file carefully same as specified in the folder.
3. Go to big query in derived table, check whether there is any table present of name "temp_notification" if it is there delete the table .
4. Run the Query from the starting

### Read the csv file

Put the notification file in the folder and type the name of the csv file.

In [0]:
# Enter the file name 
enter_name = input("Enter the name of the file :")
file_name = enter_name + ".csv"

Enter the name of the file :User_id_Gems

In [0]:
# checking the file added the excel extension or not
file_name

'User_id_Gems.csv'

In [0]:
# Reading the file
data = pd.read_csv('%s'%file_name)

In [0]:
data.dtypes

swoo_id     int64
Reward     object
dtype: object

In [0]:
# Checking the Schema of the file
data.head(10)

    swoo_id  Reward
0  14686232  5 Gems
1  14684700  5 Gems
2  11062496  5 Gems
3  14686911  5 Gems
4  14678650  5 Gems
5  14677871  5 Gems
6  14686891  5 Gems
7  14685246  5 Gems
8  14684642  5 Gems
9  14685421  5 Gems

### Loading the file into the Bigquery

**Before running the below query please make sure the table (temp_notification is not present in Big Query)**

In [0]:

data.to_gbq('processed_db.temp_notification', 
                'your-project-id',
                chunksize=None, 
                 if_exists='replace',
                 verbose=False
                 )

# processed_db = it is the db name (change it if you want to store into some other table)
# temp_notification = it is the table you want to assign

1it [00:07,  7.26s/it]

### Creating the ua_notifcation and ID of the users

In [0]:
# Writing the Sql Query 
sql_query = '''
WITH temp_table AS (
SELECT A.swoo_id, B.id, C.ua_notification_token ,c.created,
ROW_NUMBER() OVER (PARTITION BY A.swoo_id ORDER BY c.created DESC) AS row_number
FROM(
SELECT swoo_id
FROM `your-project-id.processed_db.temp_notification` ) A
LEFT JOIN(
SELECT handle, id
FROM  `your-project-id.master_tables.user` 
GROUP BY 1,2) B
ON A.swoo_id = B.id
LEFT JOIN(
SELECT user_id , ua_notification_token, created
FROM `your-project-id.master_tables.user_device` 
ORDER BY created DESC) C
ON B.id = C.user_id)

SELECT * FROM temp_table
WHERE row_number = 1
'''

In [0]:
# Running query in the BIG_QUERY
data_frame = pd.read_gbq(sql_query, project_id=project_id, reauth=True, private_key=private_key, dialect='standard')

In [0]:
data_frame.head(10)

,swoo_id,id,ua_notification_token,created,row_number
0,13774,13774,a1fe22b5-bfcf-4cf1-a516-9bc244377b55,2018-12-01 22:51:29+00:00,1
1,16055,16055,6b7ec72f-789f-4914-881b-b75441954b1f,2019-05-11 09:26:51+00:00,1
2,23532,23532,b9c39ac5-7dfe-41ac-a7da-d3b333aa1a56,2019-05-12 10:30:28+00:00,1
3,31641,31641,217a959c-8c12-4c91-8430-9af16caf5e4f,2019-05-11 10:46:32+00:00,1
4,45742,45742,87eb1bb3-2bb0-4b8d-9132-6388ff7ca78a,2019-05-22 14:07:57+00:00,1
5,98673,98673,aeb3906f-181e-46ef-9e2c-a9fe149de5c4,2019-05-27 14:28:39+00:00,1
6,141530,141530,64295dd7-be28-4c71-9785-5c1a6a47abc2,2017-11-16 02:18:46+00:00,1
7,141943,141943,1f7bbead-35fd-48bd-9ccf-d7df5e7d45e1,2017-11-16 02:46:58+00:00,1
8,233597,233597,2dd99da7-0b12-46b2-94e7-76a1da996200,2019-05-09 09:43:17+00:00,1
9,268026,268026,ade8fc7c-1981-442b-bc43-48b0b194b0e4,2019-04-29 07:47:29+00:00,1

In [0]:
data_first = data[["swoo_id","Reward"]]
data_second = data_frame[["swoo_id","id","ua_notification_token"]]

In [0]:
data_final = pd.merge(data_first,data_second,on = "swoo_id",how = "left")

In [0]:
data_final

        swoo_id  Reward        id                 ua_notification_token
0      14686232  5 Gems  14686232  0b72171d-a8b8-4d5a-aa7d-c3b1eb539eca
1      14684700  5 Gems  14684700  55c53f50-9ed2-462e-9990-5fcb86347cf6
2      11062496  5 Gems  11062496  10bca672-5794-46c5-bfea-1a5a582573ba
3      14686911  5 Gems  14686911  6ed1e98c-b5f3-43c6-a782-573ff829f292
4      14678650  5 Gems  14678650  f9aa33c8-ed1f-427f-b4d8-9f98038fc129
5      14677871  5 Gems  14677871  22b460d4-795e-4545-85e8-f5d7e44bf58f
6      14686891  5 Gems  14686891  80f0821e-d8db-471f-87f9-c432d355b834
7      14685246  5 Gems  14685246  e5958570-1350-4a16-b1eb-4ffb31fb6247
8      14684642  5 Gems  14684642  aac2c5d7-0c66-46a9-8b7a-59780c93bcae
9      14685421  5 Gems  14685421  8a214c04-db24-4842-9d90-89dd314a3371
10     14268741  5 Gems  14268741  fffec77e-9a0b-447d-aa39-5cfdc7557519
11     14684462  5 Gems  14684462  0506d0d3-e6b8-4247-9718-e0748dc036bf
12     14686616  5 Gems  14686616  e6ff8e32-ad97-41db-affc-d841ca0d768a
13     11122552  5 Gems  11122552  6cd3983a-59dd-4644-886e-a2968d4447b1
14     10751389  5 Gems  10751389  4a7624d3-9d7c-4229-89e1-26c2041deeb8
15     11777608  5 Gems  11777608  e5c558e2-6ea0-416f-b82a-5cb0fcdb5401
16     14678960  5 Gems  14678960  e5c558e2-6ea0-416f-b82a-5cb0fcdb5401
17     10604256  5 Gems  10604256  bb009903-ffe0-474c-a053-273f47613622
18     14685592  5 Gems  14685592  dbb2121e-9862-4c9f-aae9-dd90125850dd
19     13779002  5 Gems  13779002  d63bb42d-3aae-426f-8d57-2377e439f697
20     14669782  5 Gems  14669782  d63bb42d-3aae-426f-8d57-2377e439f697
21     14689430  5 Gems  14689430  e2cef424-414b-4ea3-8076-4c899e3f1d08
22     14689442  5 Gems  14689442  e2cef424-414b-4ea3-8076-4c899e3f1d08
23     14687839  5 Gems  14687839  fdcf1bed-9200-402f-b281-9101822b4758
24     14687834  5 Gems  14687834  fdcf1bed-9200-402f-b281-9101822b4758
25     14684571  5 Gems  14684571  7dd622fb-f98b-4646-b653-4f0c861d9ac0
26      9702306  5 Gems   9702306  bb629577-6154-4dd5-b75d-486fb3386337
27     14689668  5 Gems  14689668  76a3e9d4-6cf5-4b9c-af88-8469e02d531e
28      9839601  5 Gems   9839601  b831d8bb-301d-4562-a1cf-13b7d7f3d941
29      4887396  5 Gems   4887396  100e996e-ee57-46c2-99fb-987a65295bbc
...         ...     ...       ...                                   ...
15601  14686138  5 Gems  14686138  4448594b-005b-470c-a711-f664e3443f34
15602  14701797  5 Gems  14701797  75ee59b8-2f88-48a3-b8ff-a3f17299dd2b
15603  14693361  5 Gems  14693361  792cbb0e-0688-44e6-afa9-42dd8b1e35fe
15604  14693367  5 Gems  14693367  792cbb0e-0688-44e6-afa9-42dd8b1e35fe
15605  14695148  5 Gems  14695148  99d19bca-0fb4-421b-925d-52c94f2d2d84
15606  14694446  5 Gems  14694446  9eac76c1-be39-42c4-a089-a7b4a024d216
15607  14693553  5 Gems  14693553  84cb240e-294a-46dc-8a2e-2a3a892cde1d
15608  12252543  5 Gems  12252543  586ba00b-1e5b-4f82-b961-4551a7816abe
15609  14711954  5 Gems  14711954  1bbbcd24-723a-4378-b77d-07291fef8cee
15610  14712080  5 Gems  14712080  1bf2ec14-82ff-4d5a-95e5-45c971042944
15611  14711537  5 Gems  14711537  2e0a2818-c658-4d1b-8672-a7491ee1682f
15612  14707714  5 Gems  14707714  cefc3f0a-df66-4963-b9c2-cf2f21210c0a
15613  14710355  5 Gems  14710355  88ff598e-fe6c-4a1e-9678-b22c4b24839d
15614  14710229  5 Gems  14710229  dd291cb3-c7af-4db5-aa03-e8d49b53fb4f
15615   6879643  5 Gems   6879643  4f2635d9-7a91-46bd-81a6-13f779ec1ffe
15616  14711368  5 Gems  14711368  87aa1686-cf9e-462d-b946-c41c5e391bdf
15617  14710572  5 Gems  14710572  874cd027-cc15-4f9d-9c42-0a2d0ed750b0
15618  14709650  5 Gems  14709650  d89e9965-f8ef-4553-b5db-17f8947793ac
15619  14714591  5 Gems  14714591  16188374-fb49-48fd-a8bd-947e8d633355
15620  14713104  5 Gems  14713104  04149c75-3aac-47b7-8e7c-39bbaf21d69f
15621  14714574  5 Gems  14714574  5fee749c-f478-44a3-b3f5-e09b77849f59
15622  14714569  5 Gems  14714569  5fee749c-f478-44a3-b3f5-e09b77849f59
15623  14717024  5 Gems  14717024  a137add5-ec9e-491e-93a6-551e8c1da5b9
15624  14714378  5 Gems  14714378  a4c2ec29-97ec-4806-810b-1d1c0ab818e7
15625  14714371  5 Gems  14714371  a4c2ec29-97ec-4806-810b-1d1c0ab818e7
15626  14717075  5 Gems  14717075  fafe17f9-53a5-4214-90d9-57dd3432e2a5
15627  14716763  5 Gems  14716763  c0be6fba-e19c-48bb-95c8-9ab6d9a5e33f
15628  14716889  5 Gems  14716889  c0be6fba-e19c-48bb-95c8-9ab6d9a5e33f
15629  14713620  5 Gems  14713620  da835cea-c2cf-4fdf-a3fe-230c1a8f0587
15630  14713605  5 Gems  14713605  da835cea-c2cf-4fdf-a3fe-230c1a8f0587

[15631 rows x 4 columns]

In [0]:
data_final.to_csv("%s"%file_name)

In [0]:
data_final.isnull().sum()

swoo_id                   0
Reward                    0
id                        0
ua_notification_token    53
dtype: int64

**You will get the most the of the values for values which are coming as NaN just use the below link for the ua_notification**

**Type the swoo_id after users/**

http://gaming-oncall.swoo.tv:3000/swoo/users/

In [0]:
data_final.shape

(15631, 4)